import type { WorldBookEntry } from "@/types";

export interface PresetWorldBook {
  id: string;
  name: string;
  theme: string;
  description: string;
  tags: string[];
  violationWords: string[];
  entries: Omit<WorldBookEntry, "id" | "uid" | "createdAt" | "updatedAt">[];
}

// 修仙世界 - 男频热门
const xianxia: PresetWorldBook = {
  id: "wb-builtin-xianxia",
  name: "修仙世界",
  theme: "玄幻修仙",
  description: "以中国传统道教文化为基础的修仙世界，包含炼气、筑基、金丹、元婴等境界体系",
  tags: ["修仙", "玄幻", "东方", "男频"],
  violationWords: ["手机", "电脑", "现代", "科技", "网络", "电"],
  entries: [
    {
      category: "境界体系",
      title: "修仙境界",
      key: ["境界", "修为", "等级", "境界划分"],
      content: "修仙境界从低到高依次为：炼气期、筑基期、金丹期、元婴期、化神期、炼虚期、合体期、大乘期、渡劫期。每个大境界又分初期、中期、后期、巅峰四个小境界。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "境界体系",
      title: "炼气期",
      key: ["炼气", "炼气期"],
      content: "炼气期为修仙入门，共分九层。炼气期修士可感应天地灵气，引气入体，初步掌握基础法术。寿命约百岁。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "境界体系",
      title: "筑基期",
      key: ["筑基", "筑基期"],
      content: "筑基期是修仙第一道坎，将体内真气淬炼凝成真元，打通任督二脉。筑基期修士可御器飞行，施展中等法术。寿命约二百年。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "境界体系",
      title: "金丹期",
      key: ["金丹", "金丹期", "结丹"],
      content: "金丹期修士凝聚真元成丹，实力质变。可御剑千里，施放大范围法术，丹成后寿元五百年。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "境界体系",
      title: "元婴期",
      key: ["元婴", "元婴期"],
      content: "元婴期修士金丹破而元婴出，可夺舍重生。一人之下万人之上的地位，寿元千年。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "势力架构",
      title: "宗门体系",
      key: ["宗门", "门派", "势力"],
      content: "修仙界势力分为：散修、家族、宗门、圣地、仙朝。宗门设有掌门、长老、内门弟子、外门弟子、杂役弟子等层级。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "势力架构",
      title: "修真家族",
      key: ["家族", "世家"],
      content: "修真家族以血缘为纽带，世代传承修炼功法。家族内有嫡系庶族之分，核心资源由嫡系掌控。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "修炼资源",
      title: "灵气与灵脉",
      key: ["灵气", "灵脉", "灵地"],
      content: "灵气是修仙之本，天地间灵气浓度因地域而异。灵脉汇聚之地为灵地，宗门选址必依灵脉。修炼需吸收灵气淬炼肉身。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "修炼资源",
      title: "灵石与丹药",
      key: ["灵石", "丹药", "灵丹"],
      content: "灵石为修仙界通用货币，分下品、中品、上品、极品。丹药按品级分一至九品，可辅助修炼、疗伤、突破。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "修炼资源",
      title: "法器与法宝",
      key: ["法器", "法宝", "灵器"],
      content: "法器分低阶、中阶、高阶、极品、灵宝。法宝有灵，可认主。剑修常用飞剑，丹修手持丹炉，阵师布置阵旗。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "世界观",
      title: "修仙世界基本法则",
      key: ["修仙", "修道", "仙缘"],
      content: "修仙者以飞升成仙为终极目标。天道有常，因果循环。修道者需看破虚妄，累积功德，最终超脱凡尘。逆天而行者必遭天谴。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "世界观",
      title: "凡人与修士",
      key: ["凡人", "普通人", "世俗"],
      content: "凡人不知修仙之事，修士超然物外。但也有修士行走世俗、红尘炼心。凡人与修士之间有巨大的认知鸿沟。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "人物设定",
      title: "宗门弟子日常",
      key: ["弟子", "内门", "外门", "杂役"],
      content: "弟子需完成宗门任务赚取贡献点兑换资源。内门弟子地位高于外门，享受更好修炼条件。杂役弟子负责打扫、采药等杂事。",
      constant: false,
      selective: true,
      order: 50,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "人物设定",
      title: "修仙者称谓",
      key: ["前辈", "道友", "师兄", "师姐", "师叔"],
      content: "同辈互称道友，晚辈称长辈为前辈/师叔/师伯，同门称师兄师姐。散修之间多以道号相称。",
      constant: false,
      selective: true,
      order: 50,
      position: "situation",
      insertionDepth: 20,
      disable: false,
    },
    {
      category: "特殊设定",
      title: "天劫",
      key: ["天劫", "天雷", "渡劫"],
      content: "每次大境界突破都有天劫考验。心魔劫考校心性，雷劫考验肉身。渡劫失败者灰飞烟灭，成功者境界大成。",
      constant: false,
      selective: false,
      order: 40,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
  ],
};

// 无限流 - 男频热门
const infinite: PresetWorldBook = {
  id: "wb-builtin-infinite",
  name: "无限流世界",
  theme: "无限流",
  description: "穿梭于各个影视、小说、游戏世界完成任务的无限流世界观",
  tags: ["无限流", "诸天", "副本", "男频"],
  violationWords: [],
  entries: [
    {
      category: "体系设定",
      title: "主神空间",
      key: ["主神", "系统", "空间", "任务"],
      content: "主角被选中进入主神空间，需进入各个副本世界完成任务。完成任务可获得点数、支线剧情、血统兑换奖励。死亡即真亡。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "体系设定",
      title: "副本世界类型",
      key: ["副本", "世界", "位面"],
      content: "副本世界涵盖：武侠、仙侠、末日、科幻、灵异、游戏、影视等。难度从E到S+递增。高难度副本奖励丰厚但死亡率极高。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "体系设定",
      title: "兑换系统",
      key: ["兑换", "商城", "兑换券", "点数"],
      content: "通关奖励可兑换：血统（吸血鬼、狼人、修仙体质等）、技能（武功、异能、魔法）、道具（武器、防具、消耗品）、称号。S级以上兑换需支线剧情。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "体系设定",
      title: "队伍与队友",
      key: ["队伍", "队友", "团战"],
      content: "可组建小队共同进入副本。小队有队长、成员之分。队长获得额外奖励但承担更多责任。新人常以跟随者身份加入老手队伍。",
      constant: false,
      selective: true,
      order: 30,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "等级体系",
      title: "轮回者等级",
      key: ["等级", "轮回者", "资深者"],
      content: "轮回者按通关副本数和积分分为：新人（1-3副本）、资深者（4-10副本）、老鸟（11-50副本）、强者（50+副本）。等级影响可进入的副本难度。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "等级体系",
      title: "血统等级",
      key: ["血统", "血脉", "种族"],
      content: "血统分D到S+级。D级如普通武者，C级如精英武者，B级如忍者/海盗，A级如吸血鬼贵族，S级如纯血种，S+级为传说级血统。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "核心规则",
      title: "任务类型",
      key: ["任务", "主线", "支线"],
      content: "副本任务分：主线任务（必须完成，失败则全队抹杀）、支线任务（可选，完成额外奖励）、隐藏任务（触发条件未知，奖励最丰厚）。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "核心规则",
      title: "死亡机制",
      key: ["死亡", "抹杀", "复活"],
      content: "在副本中死亡即被抹杀。除非拥有复活道具或队友掌握复活技能。复活类物品极其稀有，是保命底牌。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "核心规则",
      title: "时间流速",
      key: ["时间", "流速", "外界"],
      content: "副本内时间流速与外界不同。外界可能只过了几秒，副本内已过数月。每次回归主神空间后有休整时间，可准备物资、学习技能。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "人物设定",
      title: "主神空间氛围",
      key: ["空间", "广场", "大厅"],
      content: "主神空间广场巨大，有各种建筑：兑换商店、训练场、交易市场。轮回者之间竞争激烈，弱者被淘汰，强者生存。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
  ],
};

// 娱乐圈 - 女频热门
const entertainment: PresetWorldBook = {
  id: "wb-builtin-entertainment",
  name: "娱乐圈世界",
  theme: "现代都市·娱乐圈",
  description: "现代都市背景下的明星、艺人、偶像、演员的娱乐圈生态",
  tags: ["娱乐圈", "明星", "都市", "女频"],
  violationWords: ["灵气", "修仙", "法术", "魔法", "异能"],
  entries: [
    {
      category: "行业设定",
      title: "娱乐圈生态",
      key: ["娱乐圈", "行业", "圈"],
      content: "娱乐圈由经纪公司、艺人、媒体、粉丝四大部分组成。艺人分为歌手、演员、偶像、综艺人。顶级艺人被称为天王/天后。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "行业设定",
      title: "经纪公司",
      key: ["经纪公司", "公司", "签约"],
      content: "艺人签约经纪公司，公司负责资源对接、形象包装、商务洽谈。分成比例通常公司六艺人四。顶级公司掌握着最好的资源。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "行业设定",
      title: "流量与热度",
      key: ["流量", "热度", "数据", "话题"],
      content: "娱乐圈以流量论英雄。热搜、话题量、播放量、票房是衡量艺人价值的硬指标。数据好代表商业价值高，资源会主动找上门。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "行业设定",
      title: "粉丝文化",
      key: ["粉丝", "粉丝团", "应援"],
      content: "粉丝是艺人的基本盘。粉丝团有站姐、应援、打榜、控评等组织化行为。粉丝与艺人之间是情感绑定的关系。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "职业发展",
      title: "偶像出道",
      key: ["偶像", "出道", "练习生"],
      content: "偶像通过选秀或练习生出道，以唱跳为主要才艺。出道后发行专辑、参加综艺、开演唱会。偶像生命周期短，需要转型演员或歌手。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "职业发展",
      title: "演员之路",
      key: ["演员", "拍戏", "演戏", "剧组"],
      content: "演员从跑龙套开始，逐步演配角、主角。演技派靠实力出圈，流量派靠颜值。拿奖（金鸡、金马、金像奖）是演员的终极追求。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "职业发展",
      title: "歌手之路",
      key: ["歌手", "唱歌", "专辑", "演唱会"],
      content: "歌手分为实力派和偶像派。好声音出道的歌手靠唱功，选秀出道的靠人气。专辑销量、演唱会门票、音乐奖项是衡量标准。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "人际关系",
      title: "竞争与撕逼",
      key: ["竞争", "撕逼", "黑料", "公关"],
      content: "娱乐圈竞争激烈，艺人之间明争暗斗。黑料和负面新闻是最大武器。公关团队负责危机处理，撤热搜、发声明、找水军。",
      constant: true,
      selective: true,
      order: 20,
      position: "system",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "人际关系",
      title: "潜规则",
      key: ["潜规则", "资源", "上位"],
      content: "娱乐圈存在潜规则现象。资源分配不均导致部分艺人通过不正当手段获取机会。有背景的艺人起点更高。",
      constant: false,
      selective: true,
      order: 50,
      position: "situation",
      insertionDepth: 20,
      disable: false,
    },
    {
      category: "日常设定",
      title: "艺人日常",
      key: ["行程", "通告", "赶场"],
      content: "艺人行程密集：赶通告、拍杂志、录节目、跑宣传。经常凌晨起床化妆，一天跑三四个场地。光鲜背后是高强度工作。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "日常设定",
      title: "公关话术",
      key: ["采访", "回应", "辟谣"],
      content: "艺人面对采访有标准话术：否认恋情、感谢粉丝、专注工作。涉及敏感话题时打太极、转移话题是基本技能。",
      constant: false,
      selective: true,
      order: 50,
      position: "situation",
      insertionDepth: 20,
      disable: false,
    },
  ],
};

// 宫廷古装 - 女频热门
const palace: PresetWorldBook = {
  id: "wb-builtin-palace",
  name: "宫廷古装",
  theme: "古代·宫廷",
  description: "中国古代王朝宫廷背景，皇权、后宫、权谋的交织",
  tags: ["宫廷", "古装", "权谋", "女频"],
  violationWords: ["手机", "电脑", "汽车", "现代", "电", "网络"],
  entries: [
    {
      category: "朝代背景",
      title: "架空王朝",
      key: ["王朝", "朝廷", "江山"],
      content: "架空朝代，设文武百官、六院尚书。皇帝为天子，三宫六院七十二妃。皇子夺嫡、外戚干政、宦官专权是常见政治格局。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "朝代背景",
      title: "宫廷制度",
      key: ["制度", "规矩", "礼制"],
      content: "宫廷规矩森严：见驾需行礼、称呼有讲究、后宫不得干政、前朝后宫有别。失礼者轻则受罚，重则丧命。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "后宫体系",
      title: "后宫等级",
      key: ["后宫", "妃嫔", "娘娘"],
      content: "后宫等级：皇后、皇贵妃、贵妃、妃、嫔、贵人、常在、答应。地位越高居住宫殿越好、伺候宫人越多。母以子贵。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "后宫体系",
      title: "宫斗核心",
      key: ["宫斗", "争宠", "下毒", "陷害"],
      content: "后宫争斗核心是争宠和皇子。手段包括：下毒、陷害、魅惑、借刀杀人。表面风平浪静，实则暗流涌动。一步走错满盘皆输。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "后宫体系",
      title: "太监与宫女",
      key: ["太监", "宫女", "宫人", "内侍"],
      content: "太监分等级：总管、首领、普通。宫女有掌事、普通之分。太监管传旨、服侍，宫女管梳洗、洒扫。贴身宫人最得信任。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "前朝势力",
      title: "文官集团",
      key: ["文官", "大臣", "丞相", "阁老"],
      content: "文官集团掌握朝政，分为主战主和、改革守旧等派别。丞相/首辅为文官之首。文官势力影响皇位继承。",
      constant: true,
      selective: false,
      order: 20,
      position: "system",
      insertionDepth: 70,
      disable: false,
    },
    {
      category: "前朝势力",
      title: "武将与兵权",
      key: ["武将", "将军", "兵权", "大军"],
      content: "武将掌握兵权，是朝廷的武力支柱。功高震主者易遭猜忌。边防大将手握重兵，朝廷既用又防。",
      constant: true,
      selective: false,
      order: 20,
      position: "system",
      insertionDepth: 70,
      disable: false,
    },
    {
      category: "前朝势力",
      title: "世家大族",
      key: ["世家", "门第", "士族"],
      content: "世家大族把持朝政数代，门生故吏遍布朝野。联姻是世家结盟的重要方式。皇权与世家既合作又斗争。",
      constant: true,
      selective: false,
      order: 20,
      position: "system",
      insertionDepth: 70,
      disable: false,
    },
    {
      category: "人物称谓",
      title: "皇室称谓",
      key: ["陛下", "皇上", "娘娘", "殿下"],
      content: "皇帝称陛下/皇上/万岁，皇后称皇后娘娘/母后，妃嫔称娘娘，皇子公主称殿下，太后称母后/太后。称呼错了是大不敬。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "人物称谓",
      title: "官员称谓",
      key: ["大人", "老爷", "阁老"],
      content: "对官员尊称大人/老爷，对年老资深者称阁老。下级对上级需行跪拜礼，平级以作揖为礼。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "日常细节",
      title: "宫廷饮食",
      key: ["用膳", "御膳", "膳食"],
      content: "皇帝用膳有专门御膳房，每餐数十道菜。妃嫔有各自小厨房。用膳时间有定例：早膳辰时，晚膳未时。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "日常细节",
      title: "宫廷服饰",
      key: ["朝服", "宫装", "旗装"],
      content: "皇帝穿龙袍，皇后穿凤袍，妃嫔服饰按品级有严格规定。上朝穿朝服，平日穿常服。发饰、首饰也有等级之分。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "核心冲突",
      title: "夺嫡之争",
      key: ["夺嫡", "太子", "立储"],
      content: "皇位继承是宫廷最大纷争。嫡长子继承制为理想，但现实中皇子能力、生母地位、外祖家势力、朝臣支持共同决定。",
      constant: true,
      selective: true,
      order: 15,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "核心冲突",
      title: "外戚与宦官",
      key: ["外戚", "宦官", "专权"],
      content: "外戚（太后/皇后娘家人）和宦官是皇权的延伸和威胁。皇帝用宦官牵制外朝，外戚因后妃得势掌权。三者关系微妙。",
      constant: true,
      selective: true,
      order: 20,
      position: "system",
      insertionDepth: 70,
      disable: false,
    },
  ],
};

// 恋爱模拟 - 女频热门
const romance: PresetWorldBook = {
  id: "wb-builtin-romance",
  name: "恋爱模拟世界",
  theme: "现代都市·甜宠",
  description: "现代都市背景下的浪漫恋爱模拟世界，甜宠、傲娇、霸道总裁等经典设定",
  tags: ["恋爱", "甜宠", "都市", "女频"],
  violationWords: ["灵气", "修仙", "法术", "魔法", "丧尸", "末日"],
  entries: [
    {
      category: "世界观",
      title: "现代都市背景",
      key: ["城市", "都市", "现代"],
      content: "故事发生在现代都市，有高楼大厦、咖啡厅、商场、公司、学校等场景。人们使用手机、电脑等现代科技。社会文明程度高。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "恋爱设定",
      title: "恋爱类型",
      key: ["恋爱", "喜欢", "心动", "男友"],
      content: "恋爱对象类型：霸道总裁、温柔竹马、高冷学霸、阳光暖男、腹黑天才、成熟大叔。每种类型有独特的行为模式和恋爱方式。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "恋爱设定",
      title: "恋爱进度",
      key: ["进度", "关系", "交往"],
      content: "恋爱发展阶段：初遇→好感→暧昧→告白→交往→热恋→稳定。每个阶段有不同的互动方式和心理状态。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "恋爱设定",
      title: "心动表现",
      key: ["心动", "害羞", "脸红", "心跳"],
      content: "心动时会：脸红、心跳加速、不敢对视、说话结巴、偷看对方、刻意关注。这些是恋爱初期的典型表现。",
      constant: false,
      selective: true,
      order: 30,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "角色类型",
      title: "霸道总裁",
      key: ["总裁", "霸道", "强势"],
      content: "霸道总裁：商界精英，掌控欲强，习惯用命令语气。对外冷酷无情，对女主温柔宠溺。典型台词：你只能是我的。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "角色类型",
      title: "温柔竹马",
      key: ["竹马", "青梅", "温柔"],
      content: "青梅竹马：从小一起长大，了解女主所有过去。温柔体贴，默默守护。对女主的需求了如指掌，是最温暖的依靠。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "角色类型",
      title: "高冷学霸",
      key: ["学霸", "高冷", "冰山"],
      content: "高冷学霸：成绩优异，表面冷淡疏离，实际内心柔软。不擅长表达感情，会用行动而非言语表达关心。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "角色类型",
      title: "阳光暖男",
      key: ["暖男", "阳光", "治愈"],
      content: "阳光暖男：性格开朗爱笑，是大家的开心果。善于倾听，总能给女主带来正能量。像小太阳一样温暖周围的人。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "日常场景",
      title: "约会场景",
      key: ["约会", "逛街", "电影", "吃饭"],
      content: "常见约会：咖啡厅小坐、商场逛街、看电影、公园野餐、游乐园、图书馆、博物馆。氛围温馨浪漫。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "日常场景",
      title: "社交场合",
      key: ["聚会", "派对", "朋友"],
      content: "社交场景：朋友聚会、生日派对、公司团建、同学会。在社交场合中保持得体的言行举止，是展现魅力的机会。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "情感冲突",
      title: "误会与和解",
      key: ["误会", "吵架", "冷战", "和解"],
      content: "恋爱中的常见冲突：吃醋误会、意见不合、第三者介入。关键是及时沟通解开误会，冷战不超过一天。",
      constant: false,
      selective: true,
      order: 30,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "情感冲突",
      title: "甜蜜日常",
      key: ["甜蜜", "撒糖", "恩爱"],
      content: "甜蜜表现：牵手、拥抱、亲吻、互赠礼物、做早餐、接送上下班。细节中的宠溺是最动人的。",
      constant: false,
      selective: true,
      order: 30,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
  ],
};

// 末日求生 - 男频热门
const apocalypse: PresetWorldBook = {
  id: "wb-builtin-apocalypse",
  name: "末日求生世界",
  theme: "末日·丧尸/废土",
  description: "丧尸横行或核战废土的末日世界观，人类在废墟中求生",
  tags: ["末日", "丧尸", "废土", "男频"],
  violationWords: ["修真", "法术", "灵气", "仙"],
  entries: [
    {
      category: "世界观",
      title: "末日背景",
      key: ["末日", "丧尸", "病毒", "毁灭"],
      content: "T病毒/生化泄漏导致全球丧尸化。文明崩溃，城市变废墟。幸存人类不足百分之一。没有法律秩序，只有弱肉强食。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "世界观",
      title: "丧尸设定",
      key: ["丧尸", "行尸", "怪物"],
      content: "丧尸分：普通丧尸（行动缓慢）、变异丧尸（速度极快）、巨型丧尸（力量巨大）、尸王（有智慧）。被咬伤或抓伤都会感染。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "世界观",
      title: "变异与进化",
      key: ["变异", "进化", "异能"],
      content: "部分人类感染后产生变异获得异能：力量强化、速度强化、精神力、元素控制。等级从一阶到九阶。变异者是人类的希望也是威胁。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "生存法则",
      title: "物资获取",
      key: ["物资", "食物", "补给", "搜刮"],
      content: "末日物资极度匮乏。食物、水、药品、弹药是生存关键。需要在废弃超市、仓库、医院、警局搜刮。危险与机遇并存。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "生存法则",
      title: "安全区与基地",
      key: ["安全区", "基地", "避难所"],
      content: "幸存者聚集形成安全区/基地。有军方背景的基地较为正规，民间基地靠首领个人魅力。基地有围墙、守卫、医疗、食物配给。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "生存法则",
      title: "队伍与合作",
      key: ["队伍", "同伴", "队友"],
      content: "幸存者组队行动，通常配：火力手、医疗兵、侦察兵、技术人员。团队成员可能背叛，信任是奢侈品。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "战斗体系",
      title: "武器装备",
      key: ["武器", "枪", "刀", "装备"],
      content: "武器分冷兵器（刀、棍、弩）和热兵器（手枪、步枪、霰弹枪）。弹药有限需要节约。近战武器是最后的保命手段。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "战斗体系",
      title: "异能战斗",
      key: ["异能", "能力", "强化"],
      content: "高阶异能者可以：控制元素、精神攻击、肉体强化到刀枪不入。异能越强消耗越大，需要晶核补充能量。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "人性展现",
      title: "末日人性",
      key: ["人性", "背叛", "信任"],
      content: "末日是人性的试金石。有人坚守底线保护弱者，有人为生存不择手段。信任是最大的奢侈品，背叛随时可能发生。",
      constant: true,
      selective: true,
      order: 15,
      position: "system",
      insertionDepth: 70,
      disable: false,
    },
    {
      category: "人性展现",
      title: "丧尸潮",
      key: ["尸潮", "潮涌", "大规模"],
      content: "丧尸潮是末日最大威胁，成千上万丧尸同时涌来。任何基地都可能被尸潮吞没。需要提前预警和严密防线。",
      constant: false,
      selective: false,
      order: 40,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
  ],
};

export const PRESET_WORLD_BOOKS: PresetWorldBook[] = [
  xianxia,
  infinite,
  entertainment,
  palace,
  romance,
  apocalypse,
];