import type { WorldBookEntry } from "@/types";

export interface PresetWorldBook {
  id: string;
  name: string;
  theme: string;
  description: string;
  tags: string[];
  violationWords: string[];
  entries: Omit<WorldBookEntry, "id" | "uid" | "createdAt" | "updatedAt">[];
}

// 修仙 - 男频热门
const xianxia: PresetWorldBook = {
  id: "wb-builtin-xianxia",
  name: "修仙",
  theme: "玄幻修仙",
  description: "以中国传统道教文化为基础的修仙体系，包含炼气、筑基、金丹、元婴等境界体系",
  tags: ["修仙", "玄幻", "东方", "男频"],
  violationWords: ["手机", "电脑", "现代", "科技", "网络", "电"],
  entries: [
    {
      category: "境界体系",
      title: "修仙境界",
      key: ["境界", "修为", "等级", "境界划分"],
      content: "修仙境界从低到高依次为：炼气期、筑基期、金丹期、元婴期、化神期、炼虚期、合体期、大乘期、渡劫期。每个大境界又分初期、中期、后期、巅峰四个小境界。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "境界体系",
      title: "炼气期",
      key: ["炼气", "炼气期"],
      content: "炼气期为修仙入门，共分九层。炼气期修士可感应天地灵气，引气入体，初步掌握基础法术。寿命约百岁。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "境界体系",
      title: "筑基期",
      key: ["筑基", "筑基期"],
      content: "筑基期是修仙第一道坎，将体内真气淬炼凝成真元，打通任督二脉。筑基期修士可御器飞行，施展中等法术。寿命约二百年。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "境界体系",
      title: "金丹期",
      key: ["金丹", "金丹期", "结丹"],
      content: "金丹期修士凝聚真元成丹，实力质变。可御剑千里，施放大范围法术，丹成后寿元五百年。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "境界体系",
      title: "元婴期",
      key: ["元婴", "元婴期"],
      content: "元婴期修士金丹破而元婴出，可夺舍重生。一人之下万人之上的地位，寿元千年。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "势力架构",
      title: "宗门体系",
      key: ["宗门", "门派", "势力"],
      content: "修仙界势力分为：散修、家族、宗门、圣地、仙朝。宗门设有掌门、长老、内门弟子、外门弟子、杂役弟子等层级。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "势力架构",
      title: "修真家族",
      key: ["家族", "世家"],
      content: "修真家族以血缘为纽带，世代传承修炼功法。家族内有嫡系庶族之分，核心资源由嫡系掌控。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "修炼资源",
      title: "灵气与灵脉",
      key: ["灵气", "灵脉", "灵地"],
      content: "灵气是修仙之本，天地间灵气浓度因地域而异。灵脉汇聚之地为灵地，宗门选址必依灵脉。修炼需吸收灵气淬炼肉身。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "修炼资源",
      title: "灵石与丹药",
      key: ["灵石", "丹药", "灵丹"],
      content: "灵石为修仙界通用货币，分下品、中品、上品、极品。丹药按品级分一至九品，可辅助修炼、疗伤、突破。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "修炼资源",
      title: "法器与法宝",
      key: ["法器", "法宝", "灵器"],
      content: "法器分低阶、中阶、高阶、极品、灵宝。法宝有灵，可认主。剑修常用飞剑，丹修手持丹炉，阵师布置阵旗。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "世界观",
      title: "修仙基本法则",
      key: ["修仙", "修道", "仙缘"],
      content: "修仙者以飞升成仙为终极目标。天道有常，因果循环。修道者需看破虚妄，累积功德，最终超脱凡尘。逆天而行者必遭天谴。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "世界观",
      title: "凡人与修士",
      key: ["凡人", "普通人", "世俗"],
      content: "凡人不知修仙之事，修士超然物外。但也有修士行走世俗、红尘炼心。凡人与修士之间有巨大的认知鸿沟。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "人物设定",
      title: "宗门弟子日常",
      key: ["弟子", "内门", "外门", "杂役"],
      content: "弟子需完成宗门任务赚取贡献点兑换资源。内门弟子地位高于外门，享受更好修炼条件。杂役弟子负责打扫、采药等杂事。",
      constant: false,
      selective: true,
      order: 50,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "人物设定",
      title: "修仙者称谓",
      key: ["前辈", "道友", "师兄", "师姐", "师叔"],
      content: "同辈互称道友，晚辈称长辈为前辈/师叔/师伯，同门称师兄师姐。散修之间多以道号相称。",
      constant: false,
      selective: true,
      order: 50,
      position: "situation",
      insertionDepth: 20,
      disable: false,
    },
    {
      category: "特殊设定",
      title: "天劫",
      key: ["天劫", "天雷", "渡劫"],
      content: "每次大境界突破都有天劫考验。心魔劫考校心性，雷劫考验肉身。渡劫失败者灰飞烟灭，成功者境界大成。",
      constant: false,
      selective: false,
      order: 40,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
  ],
};

// 东方玄幻 - 男频热门
const fantasy: PresetWorldBook = {
  id: "wb-builtin-fantasy",
  name: "东方玄幻",
  theme: "东方玄幻",
  description: "万族林立、古族传承与秘境遗迹交织的东方玄幻世界",
  tags: ["玄幻", "升级", "男频"],
  violationWords: ["手机", "电脑", "高铁", "直播", "网络"],
  entries: [
    {
      category: "世界观",
      title: "玄幻大陆",
      key: ["大陆", "万族", "古族"],
      content: "大陆由古老王朝、宗门圣地、妖族领地和人族城池共同构成。强者为尊，血脉、灵物、传承与机缘决定一个人的起点。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "力量体系",
      title: "境界与战力",
      key: ["境界", "战力", "修行"],
      content: "玄幻体系通常包含感气、凝元、化灵、通玄、破空等层次。境界提升不仅是灵力增长，也意味着身体、感知与神魂的全面蜕变。",
      constant: true,
      selective: false,
      order: 20,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "势力架构",
      title: "宗门王朝",
      key: ["宗门", "王朝", "家族", "圣地"],
      content: "宗门负责传承功法，王朝负责统治疆域，古族和圣地掌握稀缺资源。新一代天骄往往在试炼、秘境和大比中崭露头角。",
      constant: true,
      selective: false,
      order: 20,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "资源设定",
      title: "灵物与遗迹",
      key: ["灵物", "遗迹", "秘境", "机缘"],
      content: "灵物、古遗迹、上古秘境和稀有矿脉是玄幻世界的核心资源。机缘往往伴随风险，越是珍贵的传承越会引来争夺。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "人物设定",
      title: "天骄称谓",
      key: ["少主", "天骄", "圣子", "圣女"],
      content: "年轻一代强者常以少主、天骄、圣子、圣女等称呼。称谓不仅代表身份，也暗示背后的资源与站队。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
  ],
};

// 都市异能 - 男频热门
const urban: PresetWorldBook = {
  id: "wb-builtin-urban",
  name: "都市异能",
  theme: "现代都市·异能",
  description: "现代城市表层之下，异能觉醒、隐秘组织与暗线势力并存",
  tags: ["都市", "异能", "男频"],
  violationWords: ["修仙", "宗门", "王朝", "飞剑", "仙丹"],
  entries: [
    {
      category: "世界观",
      title: "都市表层",
      key: ["城市", "霓虹", "地铁", "写字楼"],
      content: "表层世界是普通城市生活：通勤、工作、学校、商圈和街区。真正的异能活动隐藏在阴影、夜色和监控盲区之中。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "力量体系",
      title: "异能觉醒",
      key: ["异能", "觉醒", "能力", "天赋"],
      content: "异能可由血脉、刺激、事故或某种遗传条件触发。异能通常有明确代价、冷却时间或副作用，不能无限使用。",
      constant: true,
      selective: false,
      order: 20,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "势力架构",
      title: "特殊组织",
      key: ["组织", "部门", "学院", "招募"],
      content: "都市异能世界常见组织包括官方特殊部门、民间异能组织、学院体系和地下势力。组织之间维持微妙平衡，也经常争夺觉醒者。",
      constant: true,
      selective: false,
      order: 20,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "日常设定",
      title: "暗面行动",
      key: ["夜里", "任务", "追踪", "掩护"],
      content: "异能者常在夜晚行动，处理异常事件、追踪目标、清理痕迹或执行秘密任务。白天保持普通人身份是必要的保护。",
      constant: false,
      selective: true,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "人物设定",
      title: "新人异能者",
      key: ["新人", "见习", "组长", "前辈"],
      content: "新人异能者通常要接受测试、登记和分组。前辈负责带领，组长负责分配任务，初次觉醒者则要尽快理解自己的能力边界。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
  ],
};

// 科幻星际 - 男频热门
const scifi: PresetWorldBook = {
  id: "wb-builtin-scifi",
  name: "科幻星际",
  theme: "星际科幻",
  description: "人类迈向深空后的星舰、殖民地、边疆和技术秩序",
  tags: ["科幻", "星际", "男频"],
  violationWords: ["修仙", "宗门", "王朝", "仙丹", "法术"],
  entries: [
    {
      category: "世界观",
      title: "星际时代",
      key: ["星际", "深空", "殖民", "联盟"],
      content: "人类已进入星际扩张时代，星港、殖民星、边疆站点和核心星系共同构成文明版图。不同星域之间距离巨大，交通依赖跃迁与星舰。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "交通体系",
      title: "星舰与跃迁",
      key: ["星舰", "跃迁", "航道", "曲率"],
      content: "星舰是跨星系移动的核心载体，跃迁是最常见的超远距离航行方式。航道、补给和跃迁失败都是高风险问题。",
      constant: true,
      selective: false,
      order: 20,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "势力架构",
      title: "星域势力",
      key: ["联盟", "企业", "舰队", "边疆"],
      content: "星际势力通常由联盟、军方、巨型企业、边疆据点和独立佣兵组成。资源星、航道权和技术垄断是冲突核心。",
      constant: true,
      selective: false,
      order: 20,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "职业设定",
      title: "星际职业",
      key: ["舰长", "驾驶员", "工程师", "佣兵"],
      content: "常见职业包括舰长、驾驶员、工程师、医护、侦测员与佣兵。不同职业负责不同舱段和任务，团队协作是生存前提。",
      constant: false,
      selective: true,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "特殊设定",
      title: "义体与AI",
      key: ["义体", "AI", "机械", "数据"],
      content: "部分角色会植入义体或依赖AI辅助系统。技术越先进，越会带来身份、伦理和控制权问题。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
  ],
};

// 无限流 - 男频热门
const infinite: PresetWorldBook = {
  id: "wb-builtin-infinite",
  name: "无限流",
  theme: "无限流",
  description: "穿梭于各个影视、小说、游戏世界完成任务的无限流设定",
  tags: ["无限流", "诸天", "副本", "男频"],
  violationWords: [],
  entries: [
    {
      category: "体系设定",
      title: "主神空间",
      key: ["主神", "系统", "空间", "任务"],
      content: "主角被选中进入主神空间，需进入各个副本世界完成任务。完成任务可获得点数、支线剧情、血统兑换奖励。死亡即真亡。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "体系设定",
      title: "副本世界类型",
      key: ["副本", "世界", "位面"],
      content: "副本世界涵盖：武侠、仙侠、末日、科幻、灵异、游戏、影视等。难度从E到S+递增。高难度副本奖励丰厚但死亡率极高。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "体系设定",
      title: "兑换系统",
      key: ["兑换", "商城", "兑换券", "点数"],
      content: "通关奖励可兑换：血统（吸血鬼、狼人、修仙体质等）、技能（武功、异能、魔法）、道具（武器、防具、消耗品）、称号。S级以上兑换需支线剧情。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "体系设定",
      title: "队伍与队友",
      key: ["队伍", "队友", "团战"],
      content: "可组建小队共同进入副本。小队有队长、成员之分。队长获得额外奖励但承担更多责任。新人常以跟随者身份加入老手队伍。",
      constant: false,
      selective: true,
      order: 30,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "等级体系",
      title: "轮回者等级",
      key: ["等级", "轮回者", "资深者"],
      content: "轮回者按通关副本数和积分分为：新人（1-3副本）、资深者（4-10副本）、老鸟（11-50副本）、强者（50+副本）。等级影响可进入的副本难度。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "等级体系",
      title: "血统等级",
      key: ["血统", "血脉", "种族"],
      content: "血统分D到S+级。D级如普通武者，C级如精英武者，B级如忍者/海盗，A级如吸血鬼贵族，S级如纯血种，S+级为传说级血统。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "核心规则",
      title: "任务类型",
      key: ["任务", "主线", "支线"],
      content: "副本任务分：主线任务（必须完成，失败则全队抹杀）、支线任务（可选，完成额外奖励）、隐藏任务（触发条件未知，奖励最丰厚）。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "核心规则",
      title: "死亡机制",
      key: ["死亡", "抹杀", "复活"],
      content: "在副本中死亡即被抹杀。除非拥有复活道具或队友掌握复活技能。复活类物品极其稀有，是保命底牌。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "核心规则",
      title: "时间流速",
      key: ["时间", "流速", "外界"],
      content: "副本内时间流速与外界不同。外界可能只过了几秒，副本内已过数月。每次回归主神空间后有休整时间，可准备物资、学习技能。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "人物设定",
      title: "主神空间氛围",
      key: ["空间", "广场", "大厅"],
      content: "主神空间广场巨大，有各种建筑：兑换商店、训练场、交易市场。轮回者之间竞争激烈，弱者被淘汰，强者生存。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
  ],
};

// 娱乐圈 - 女频热门
const entertainment: PresetWorldBook = {
  id: "wb-builtin-entertainment",
  name: "娱乐圈",
  theme: "现代都市·娱乐圈",
  description: "现代都市背景下的明星、艺人、偶像、演员的娱乐圈生态",
  tags: ["娱乐圈", "明星", "都市", "女频"],
  violationWords: ["灵气", "修仙", "法术", "魔法", "异能"],
  entries: [
    {
      category: "行业设定",
      title: "娱乐圈生态",
      key: ["娱乐圈", "行业", "圈"],
      content: "娱乐圈由经纪公司、艺人、媒体、粉丝四大部分组成。艺人分为歌手、演员、偶像、综艺人。顶级艺人被称为天王/天后。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "行业设定",
      title: "经纪公司",
      key: ["经纪公司", "公司", "签约"],
      content: "艺人签约经纪公司，公司负责资源对接、形象包装、商务洽谈。分成比例通常公司六艺人四。顶级公司掌握着最好的资源。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "行业设定",
      title: "流量与热度",
      key: ["流量", "热度", "数据", "话题"],
      content: "娱乐圈以流量论英雄。热搜、话题量、播放量、票房是衡量艺人价值的硬指标。数据好代表商业价值高，资源会主动找上门。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "行业设定",
      title: "粉丝文化",
      key: ["粉丝", "粉丝团", "应援"],
      content: "粉丝是艺人的基本盘。粉丝团有站姐、应援、打榜、控评等组织化行为。粉丝与艺人之间是情感绑定的关系。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "职业发展",
      title: "偶像出道",
      key: ["偶像", "出道", "练习生"],
      content: "偶像通过选秀或练习生出道，以唱跳为主要才艺。出道后发行专辑、参加综艺、开演唱会。偶像生命周期短，需要转型演员或歌手。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "职业发展",
      title: "演员之路",
      key: ["演员", "拍戏", "演戏", "剧组"],
      content: "演员从跑龙套开始，逐步演配角、主角。演技派靠实力出圈，流量派靠颜值。拿奖（金鸡、金马、金像奖）是演员的终极追求。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "职业发展",
      title: "歌手之路",
      key: ["歌手", "唱歌", "专辑", "演唱会"],
      content: "歌手分为实力派和偶像派。好声音出道的歌手靠唱功，选秀出道的靠人气。专辑销量、演唱会门票、音乐奖项是衡量标准。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "人际关系",
      title: "竞争与撕逼",
      key: ["竞争", "撕逼", "黑料", "公关"],
      content: "娱乐圈竞争激烈，艺人之间明争暗斗。黑料和负面新闻是最大武器。公关团队负责危机处理，撤热搜、发声明、找水军。",
      constant: true,
      selective: true,
      order: 20,
      position: "system",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "人际关系",
      title: "潜规则",
      key: ["潜规则", "资源", "上位"],
      content: "娱乐圈存在潜规则现象。资源分配不均导致部分艺人通过不正当手段获取机会。有背景的艺人起点更高。",
      constant: false,
      selective: true,
      order: 50,
      position: "situation",
      insertionDepth: 20,
      disable: false,
    },
    {
      category: "日常设定",
      title: "艺人日常",
      key: ["行程", "通告", "赶场"],
      content: "艺人行程密集：赶通告、拍杂志、录节目、跑宣传。经常凌晨起床化妆，一天跑三四个场地。光鲜背后是高强度工作。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "日常设定",
      title: "公关话术",
      key: ["采访", "回应", "辟谣"],
      content: "艺人面对采访有标准话术：否认恋情、感谢粉丝、专注工作。涉及敏感话题时打太极、转移话题是基本技能。",
      constant: false,
      selective: true,
      order: 50,
      position: "situation",
      insertionDepth: 20,
      disable: false,
    },
  ],
};

// 宫廷古装 - 女频热门
const palace: PresetWorldBook = {
  id: "wb-builtin-palace",
  name: "宫廷古装",
  theme: "古代·宫廷",
  description: "中国古代王朝宫廷背景，皇权、后宫、权谋的交织",
  tags: ["宫廷", "古装", "权谋", "女频"],
  violationWords: ["手机", "电脑", "汽车", "现代", "电", "网络"],
  entries: [
    {
      category: "朝代背景",
      title: "架空王朝",
      key: ["王朝", "朝廷", "江山"],
      content: "架空朝代，设文武百官、六院尚书。皇帝为天子，三宫六院七十二妃。皇子夺嫡、外戚干政、宦官专权是常见政治格局。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "朝代背景",
      title: "宫廷制度",
      key: ["制度", "规矩", "礼制"],
      content: "宫廷规矩森严：见驾需行礼、称呼有讲究、后宫不得干政、前朝后宫有别。失礼者轻则受罚，重则丧命。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "后宫体系",
      title: "后宫等级",
      key: ["后宫", "妃嫔", "娘娘"],
      content: "后宫等级：皇后、皇贵妃、贵妃、妃、嫔、贵人、常在、答应。地位越高居住宫殿越好、伺候宫人越多。母以子贵。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "后宫体系",
      title: "宫斗核心",
      key: ["宫斗", "争宠", "下毒", "陷害"],
      content: "后宫争斗核心是争宠和皇子。手段包括：下毒、陷害、魅惑、借刀杀人。表面风平浪静，实则暗流涌动。一步走错满盘皆输。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "后宫体系",
      title: "太监与宫女",
      key: ["太监", "宫女", "宫人", "内侍"],
      content: "太监分等级：总管、首领、普通。宫女有掌事、普通之分。太监管传旨、服侍，宫女管梳洗、洒扫。贴身宫人最得信任。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "前朝势力",
      title: "文官集团",
      key: ["文官", "大臣", "丞相", "阁老"],
      content: "文官集团掌握朝政，分为主战主和、改革守旧等派别。丞相/首辅为文官之首。文官势力影响皇位继承。",
      constant: true,
      selective: false,
      order: 20,
      position: "system",
      insertionDepth: 70,
      disable: false,
    },
    {
      category: "前朝势力",
      title: "武将与兵权",
      key: ["武将", "将军", "兵权", "大军"],
      content: "武将掌握兵权，是朝廷的武力支柱。功高震主者易遭猜忌。边防大将手握重兵，朝廷既用又防。",
      constant: true,
      selective: false,
      order: 20,
      position: "system",
      insertionDepth: 70,
      disable: false,
    },
    {
      category: "前朝势力",
      title: "世家大族",
      key: ["世家", "门第", "士族"],
      content: "世家大族把持朝政数代，门生故吏遍布朝野。联姻是世家结盟的重要方式。皇权与世家既合作又斗争。",
      constant: true,
      selective: false,
      order: 20,
      position: "system",
      insertionDepth: 70,
      disable: false,
    },
    {
      category: "人物称谓",
      title: "皇室称谓",
      key: ["陛下", "皇上", "娘娘", "殿下"],
      content: "皇帝称陛下/皇上/万岁，皇后称皇后娘娘/母后，妃嫔称娘娘，皇子公主称殿下，太后称母后/太后。称呼错了是大不敬。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "人物称谓",
      title: "官员称谓",
      key: ["大人", "老爷", "阁老"],
      content: "对官员尊称大人/老爷，对年老资深者称阁老。下级对上级需行跪拜礼，平级以作揖为礼。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "日常细节",
      title: "宫廷饮食",
      key: ["用膳", "御膳", "膳食"],
      content: "皇帝用膳有专门御膳房，每餐数十道菜。妃嫔有各自小厨房。用膳时间有定例：早膳辰时，晚膳未时。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "日常细节",
      title: "宫廷服饰",
      key: ["朝服", "宫装", "旗装"],
      content: "皇帝穿龙袍，皇后穿凤袍，妃嫔服饰按品级有严格规定。上朝穿朝服，平日穿常服。发饰、首饰也有等级之分。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "核心冲突",
      title: "夺嫡之争",
      key: ["夺嫡", "太子", "立储"],
      content: "皇位继承是宫廷最大纷争。嫡长子继承制为理想，但现实中皇子能力、生母地位、外祖家势力、朝臣支持共同决定。",
      constant: true,
      selective: true,
      order: 15,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "核心冲突",
      title: "外戚与宦官",
      key: ["外戚", "宦官", "专权"],
      content: "外戚（太后/皇后娘家人）和宦官是皇权的延伸和威胁。皇帝用宦官牵制外朝，外戚因后妃得势掌权。三者关系微妙。",
      constant: true,
      selective: true,
      order: 20,
      position: "system",
      insertionDepth: 70,
      disable: false,
    },
  ],
};

// 恋爱模拟 - 女频热门
const romance: PresetWorldBook = {
  id: "wb-builtin-romance",
  name: "恋爱模拟",
  theme: "现代都市·甜宠",
  description: "现代都市背景下的浪漫恋爱模拟设定，甜宠、傲娇、霸道总裁等经典设定",
  tags: ["恋爱", "甜宠", "都市", "女频"],
  violationWords: ["灵气", "修仙", "法术", "魔法", "丧尸", "末日"],
  entries: [
    {
      category: "世界观",
      title: "现代都市背景",
      key: ["城市", "都市", "现代"],
      content: "故事发生在现代都市，有高楼大厦、咖啡厅、商场、公司、学校等场景。人们使用手机、电脑等现代科技。社会文明程度高。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "恋爱设定",
      title: "恋爱类型",
      key: ["恋爱", "喜欢", "心动", "男友"],
      content: "恋爱对象类型：霸道总裁、温柔竹马、高冷学霸、阳光暖男、腹黑天才、成熟大叔。每种类型有独特的行为模式和恋爱方式。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "恋爱设定",
      title: "恋爱进度",
      key: ["进度", "关系", "交往"],
      content: "恋爱发展阶段：初遇→好感→暧昧→告白→交往→热恋→稳定。每个阶段有不同的互动方式和心理状态。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "恋爱设定",
      title: "心动表现",
      key: ["心动", "害羞", "脸红", "心跳"],
      content: "心动时会：脸红、心跳加速、不敢对视、说话结巴、偷看对方、刻意关注。这些是恋爱初期的典型表现。",
      constant: false,
      selective: true,
      order: 30,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "角色类型",
      title: "霸道总裁",
      key: ["总裁", "霸道", "强势"],
      content: "霸道总裁：商界精英，掌控欲强，习惯用命令语气。对外冷酷无情，对女主温柔宠溺。典型台词：你只能是我的。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "角色类型",
      title: "温柔竹马",
      key: ["竹马", "青梅", "温柔"],
      content: "青梅竹马：从小一起长大，了解女主所有过去。温柔体贴，默默守护。对女主的需求了如指掌，是最温暖的依靠。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "角色类型",
      title: "高冷学霸",
      key: ["学霸", "高冷", "冰山"],
      content: "高冷学霸：成绩优异，表面冷淡疏离，实际内心柔软。不擅长表达感情，会用行动而非言语表达关心。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "角色类型",
      title: "阳光暖男",
      key: ["暖男", "阳光", "治愈"],
      content: "阳光暖男：性格开朗爱笑，是大家的开心果。善于倾听，总能给女主带来正能量。像小太阳一样温暖周围的人。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "日常场景",
      title: "约会场景",
      key: ["约会", "逛街", "电影", "吃饭"],
      content: "常见约会：咖啡厅小坐、商场逛街、看电影、公园野餐、游乐园、图书馆、博物馆。氛围温馨浪漫。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "日常场景",
      title: "社交场合",
      key: ["聚会", "派对", "朋友"],
      content: "社交场景：朋友聚会、生日派对、公司团建、同学会。在社交场合中保持得体的言行举止，是展现魅力的机会。",
      constant: false,
      selective: true,
      order: 40,
      position: "situation",
      insertionDepth: 30,
      disable: false,
    },
    {
      category: "情感冲突",
      title: "误会与和解",
      key: ["误会", "吵架", "冷战", "和解"],
      content: "恋爱中的常见冲突：吃醋误会、意见不合、第三者介入。关键是及时沟通解开误会，冷战不超过一天。",
      constant: false,
      selective: true,
      order: 30,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "情感冲突",
      title: "甜蜜日常",
      key: ["甜蜜", "撒糖", "恩爱"],
      content: "甜蜜表现：牵手、拥抱、亲吻、互赠礼物、做早餐、接送上下班。细节中的宠溺是最动人的。",
      constant: false,
      selective: true,
      order: 30,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
  ],
};

// 末日求生 - 男频热门
const apocalypse: PresetWorldBook = {
  id: "wb-builtin-apocalypse",
  name: "末日求生",
  theme: "末日·丧尸/废土",
  description: "丧尸横行或核战废土的末日世界观，人类在废墟中求生",
  tags: ["末日", "丧尸", "废土", "男频"],
  violationWords: ["修真", "法术", "灵气", "仙"],
  entries: [
    {
      category: "世界观",
      title: "末日背景",
      key: ["末日", "丧尸", "病毒", "毁灭"],
      content: "T病毒/生化泄漏导致全球丧尸化。文明崩溃，城市变废墟。幸存人类不足百分之一。没有法律秩序，只有弱肉强食。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "世界观",
      title: "丧尸设定",
      key: ["丧尸", "行尸", "怪物"],
      content: "丧尸分：普通丧尸（行动缓慢）、变异丧尸（速度极快）、巨型丧尸（力量巨大）、尸王（有智慧）。被咬伤或抓伤都会感染。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "世界观",
      title: "变异与进化",
      key: ["变异", "进化", "异能"],
      content: "部分人类感染后产生变异获得异能：力量强化、速度强化、精神力、元素控制。等级从一阶到九阶。变异者是人类的希望也是威胁。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "生存法则",
      title: "物资获取",
      key: ["物资", "食物", "补给", "搜刮"],
      content: "末日物资极度匮乏。食物、水、药品、弹药是生存关键。需要在废弃超市、仓库、医院、警局搜刮。危险与机遇并存。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "生存法则",
      title: "安全区与基地",
      key: ["安全区", "基地", "避难所"],
      content: "幸存者聚集形成安全区/基地。有军方背景的基地较为正规，民间基地靠首领个人魅力。基地有围墙、守卫、医疗、食物配给。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "生存法则",
      title: "队伍与合作",
      key: ["队伍", "同伴", "队友"],
      content: "幸存者组队行动，通常配：火力手、医疗兵、侦察兵、技术人员。团队成员可能背叛，信任是奢侈品。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 80,
      disable: false,
    },
    {
      category: "战斗体系",
      title: "武器装备",
      key: ["武器", "枪", "刀", "装备"],
      content: "武器分冷兵器（刀、棍、弩）和热兵器（手枪、步枪、霰弹枪）。弹药有限需要节约。近战武器是最后的保命手段。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "战斗体系",
      title: "异能战斗",
      key: ["异能", "能力", "强化"],
      content: "高阶异能者可以：控制元素、精神攻击、肉体强化到刀枪不入。异能越强消耗越大，需要晶核补充能量。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "人性展现",
      title: "末日人性",
      key: ["人性", "背叛", "信任"],
      content: "末日是人性的试金石。有人坚守底线保护弱者，有人为生存不择手段。信任是最大的奢侈品，背叛随时可能发生。",
      constant: true,
      selective: true,
      order: 15,
      position: "system",
      insertionDepth: 70,
      disable: false,
    },
    {
      category: "人性展现",
      title: "丧尸潮",
      key: ["尸潮", "潮涌", "大规模"],
      content: "丧尸潮是末日最大威胁，成千上万丧尸同时涌来。任何基地都可能被尸潮吞没。需要提前预警和严密防线。",
      constant: false,
      selective: false,
      order: 40,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
  ],
};

// 民俗悬疑 - 男频热门（捞尸人/民俗怪谈）
const folklore: PresetWorldBook = {
  id: "wb-builtin-folklore",
  name: "民俗悬疑",
  theme: "民俗悬疑",
  description: "江河湖海、山村水乡之间，隐藏着古老的行业与禁忌：捞尸人、阴阳先生、赶尸人……敬畏传统，小心诡事",
  tags: ["民俗", "悬疑", "灵异", "男频"],
  violationWords: ["手机", "电脑", "互联网", "科技", "科学", "实验室", "研究", "程序"],
  entries: [
    {
      category: "世界概要",
      title: "民俗世界",
      key: ["世界", "江湖", "行当"],
      content: "这是一个充满民间禁忌与古老行当的世界：江河有河神，山野有山魈，坟地有阴气。捞尸人、赶尸人、阴阳先生、算命先生等古老职业仍在乡野间传承，规矩繁多，违者不祥。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "硬性规则",
      title: "行业规矩",
      key: ["规矩", "行规", "忌讳"],
      content: "各行当皆有铁律：捞尸人入水前要烧纸叩拜，尸体出水不能看脸；阴阳先生开坛做法需净手焚香；夜路不回头，饭桌不摆三根筷子。破规矩者，轻则倒霉，重则丧命。",
      constant: true,
      selective: false,
      order: 15,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "水域禁忌",
      title: "河神与溺亡",
      key: ["河", "水", "江", "湖", "船", "渡"],
      content: "江河湖泊皆有河神。溺亡之人魂魄困于水中，需捞尸人用红绳牵引才能归岸。行船忌说「翻」字，渡口深夜不接客，河边晾晒红衣是大忌。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "捞尸行当",
      title: "捞尸人",
      key: ["捞尸", "尸体", "浮尸", "打捞"],
      content: "捞尸人是与阴间打交道的行当：尸体入水三日不腐是怨气未消，捞出后要诵往生咒；无名尸要立坟埋骨，否则会回来寻人。每一具尸体背后都有故事。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "山野怪谈",
      title: "山村禁忌",
      key: ["村", "坟", "上坟", "山神庙", "赶集"],
      content: "山村禁忌繁多：夜半不上山，坟头草不拔，山神庙里不喧哗；婴儿夜里啼哭要贴符；新坟三年不迁。外来人进村，先拜土地爷，再问村中忌讳。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "灵异事件",
      title: "怨灵",
      key: ["冤魂", "怨气", "鬼", "阴气", "索命"],
      content: "怨灵是含冤而死之人的执念所化，常盘踞在死亡之地。怨气越重，怨灵越凶。普通人对付不了怨灵，只能请阴阳先生超度，或找出其生前冤屈。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "灵异事件",
      title: "诅咒与中邪",
      key: ["诅咒", "中邪", "符", "做法", "降头"],
      content: "民间流传着各种咒术：扎小人、写八字、撒米咒。中邪之人神志不清、口吐胡言，需符水、朱砂、公鸡血破解。咒术害人者自身也会折损阳寿。",
      constant: false,
      selective: false,
      order: 40,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "古老职业",
      title: "阴阳先生",
      key: ["先生", "阴阳", "算命", "看风水", "收徒"],
      content: "阴阳先生精通命理风水、驱邪镇宅，是民间地位最高的神秘职业。先生收徒看缘分，传艺有戒律：不害人、不贪财、不泄露天机。晚年多半孤独，与鬼打交道者折寿。",
      constant: false,
      selective: false,
      order: 40,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
  ],
};

// 规则怪谈 - 男频热门（规则生存 / 异常空间）
const rulehorror: PresetWorldBook = {
  id: "wb-builtin-rulehorror",
  name: "规则怪谈",
  theme: "规则怪谈",
  description: "隐秘降临的世界——每一处空间都有规则，每一条规则背后都是生存的代价。违反规则，就会被「它」带走",
  tags: ["规则", "怪谈", "生存", "男频"],
  violationWords: ["科学", "科技", "实验室", "法律", "法院", "警察局"],
  entries: [
    {
      category: "世界概要",
      title: "世界规则",
      key: ["世界", "诡异", "怪谈", "降临"],
      content: "异常现象从某一天起开始出现：异常空间、无法解释的事件、消失的人。人类用规则对抗未知——只要不违反规则，就能活下来。规则是这个世界唯一的真理。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "硬性规则",
      title: "生存法则",
      key: ["生存", "法则", "保命"],
      content: "生存铁律：① 永远遵守规则，哪怕它看起来荒谬；② 不要回应深夜的敲门声；③ 看到第二个自己立刻离开；④ 规则与常识冲突时，相信规则；⑤ 不要告诉任何人你看到了什么。",
      constant: true,
      selective: false,
      order: 15,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "诡异规则",
      title: "规则清单",
      key: ["规则", "守则", "条例", "须知", "清单"],
      content: "每个诡异空间都贴有规则清单，用红色或黑色字体写着注意事项。规则内容往往诡异（如「凌晨三点不要照镜子」「不要给电梯里的红衣女人让座」）。违反任何一条，都会触发不可逆的后果。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 70,
      disable: false,
    },
    {
      category: "禁忌事项",
      title: "绝对禁止",
      key: ["禁止", "千万别", "不能", "不要", "禁忌"],
      content: "禁忌事项是规则的延伸：不要回头看身后的声音；不要在午夜答应陌生人的请求；不要捡起地上的钞票；不要数楼梯的台阶。好奇心是规则怪谈中最致命的死法。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "空间划分",
      title: "异常区域",
      key: ["区域", "楼层", "房间", "走廊", "地下室"],
      content: "诡异空间有自己的「领地」：某层楼永远亮着红灯、某间房总是打不开、地下室的楼梯多出一级。异常区域的时间流速和外界不同，误入者要按区域规则行事才能离开。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "异常事件",
      title: "诡异事件",
      key: ["异常", "怪事", "不对劲", "消失", "重复"],
      content: "诡异事件是规则的执行者：墙上出现新字迹、白天播放的旧广播、突然安静下来的街道。事件发生前往往有征兆——滴水声、钟表声、脚步声。资深者会提前察觉并避开。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "生存空间",
      title: "安全区",
      key: ["安全区", "庇护所", "避难", "灯火"],
      content: "安全区是规则之外的一小片净土：通常是有活人守夜的房间、贴着符纸的门内、或完全符合规则清单的空间。安全区也会收缩——每过一夜，诡异就前进一点。",
      constant: false,
      selective: false,
      order: 40,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "未知存在",
      title: "它们",
      key: ["它", "管理员", "巡查", "工作人员", "东西"],
      content: "规则背后是「它们」——形态模糊的存在，遵守规则的人看不到它们，违反规则的人会成为它们。工作人员、管理员、巡查员，可能是人，也可能只是披着人皮的规则。",
      constant: false,
      selective: false,
      order: 40,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
  ],
};

// 古言宅斗 - 女频热门（宅斗/家族内宅）
const zhaidou: PresetWorldBook = {
  id: "wb-builtin-zhaidou",
  name: "古言宅斗",
  theme: "古言宅斗",
  description: "古代世家大族的内宅深院：嫡庶有别，妻妾相争，一草一木皆是博弈。步步为营，方能安身立命",
  tags: ["古言", "宅斗", "世家", "女频"],
  violationWords: ["手机", "电脑", "互联网", "公司", "老板", "银行", "汽车", "飞机"],
  entries: [
    {
      category: "世界概要",
      title: "世家大族",
      key: ["世家", "家族", "宅院", "府邸"],
      content: "故事发生在古代世家大族的内宅深院。家族以宗法礼教为纲，男子在外为官经商，女子在内掌中馈、理家务。内宅即是战场——请安、赏赐、人情往来，处处皆是博弈。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "宗法制度",
      title: "嫡庶与礼法",
      key: ["嫡", "庶", "宗法", "礼法", "长幼"],
      content: "宗法森严：嫡出高于庶出，长幼有序，尊卑有别。庶出子女见嫡母需行大礼，妾室在正妻面前只能自称「奴」。逾越礼法者，轻则被斥责，重则逐出家门。",
      constant: true,
      selective: false,
      order: 15,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "内宅格局",
      title: "妻妾等级",
      key: ["妻", "妾", "通房", "姨娘", "正室"],
      content: "内宅等级分明：正妻掌家，妾室服侍，通房丫鬟地位最低。正妻可随意处置妾室的月例与份例，妾室得宠可越级，但名分终究低人一等。妻妾相争是宅斗永恒的主题。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "家规礼数",
      title: "家规与请安",
      key: ["家规", "家法", "规矩", "请安", "晨昏定省"],
      content: "每日晨昏定省是内宅铁律：晨起向长辈请安，晚间歇息前再行一礼。家规森严者连坐姿、用膳、说话声量都有讲究。触犯家规者，罚跪祠堂、抄家训、扣月例，都是家常便饭。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "联姻婚嫁",
      title: "联姻规则",
      key: ["联姻", "婚嫁", "定亲", "提亲", "嫁妆"],
      content: "世家联姻关乎家族兴衰：高门联姻讲门当户对，低门高嫁靠嫁妆与陪嫁。婚约定下后反悔，是结死仇。嫁妆是女子的私产与底气，嫁妆丰厚者在内宅说话都硬气三分。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "中馈掌家",
      title: "中馈与月例",
      key: ["中馈", "账房", "月例", "管家", "庄子"],
      content: "掌中馈者掌家权：管账房、发月例、理庄子铺子。中馈之权是内宅女子安身立命之本，交接时明里盘账暗里斗法。克扣月例、做假账、吞没嫁妆，都是宅斗的刀光剑影。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "人情世故",
      title: "内宅人脉",
      key: ["人情", "赏赐", "妯娌", "姑嫂", "嬷嬷"],
      content: "内宅是人情织成的网：嬷嬷丫鬟是眼线，妯娌姑嫂是同盟也是对手，赏赐是拉拢也是立威。一句话传三个耳就是另一番意思，贴身丫鬟背叛比敌人更致命。",
      constant: false,
      selective: false,
      order: 40,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "宅院布局",
      title: "深宅院落",
      key: ["正院", "跨院", "角门", "后花园", "祠堂"],
      content: "世家宅邸格局森严：正院住嫡系长辈，跨院住各房，偏院安置不受宠的妾室庶出。角门通往街市，后花园是小姐们唯一能透气的去处。祠堂供奉祖宗牌位，罚跪常在祠堂。",
      constant: false,
      selective: false,
      order: 40,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
  ],
};

// 重生年代 - 女频热门（大国日化/草原牧医/年代文）
const retro: PresetWorldBook = {
  id: "wb-builtin-retro",
  name: "重生年代",
  theme: "重生年代",
  description: "重回七八十年代：供销社、粮票、下乡、高考……这一次，要抓住每一个改变命运的机会",
  tags: ["年代", "重生", "奋斗", "女频"],
  violationWords: ["手机", "电脑", "互联网", "微信", "支付宝", "外卖", "高铁"],
  entries: [
    {
      category: "时代背景",
      title: "七八十年代",
      key: ["年代", "七十年代", "八十年代", "当时", "那个年代"],
      content: "故事发生在七十年代末到八十年代初：城市里筒子楼连片，农村靠工分吃饭；物资凭票供应，自行车、收音机是家里的大件。社会正在剧变，处处是机会。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "经济体系",
      title: "票证经济",
      key: ["粮票", "布票", "油票", "凭票", "供应"],
      content: "计划经济时代，买粮要粮票、买布要布票、买油要油票，肥皂火柴也要凭证。票证比钱还金贵，黑市倒卖票证是重罪。谁家有「工业券」，谁家就体面。",
      constant: true,
      selective: false,
      order: 15,
      position: "system",
      insertionDepth: 90,
      disable: false,
    },
    {
      category: "城乡生活",
      title: "供销社",
      key: ["供销社", "百货", "柜台", "售货员"],
      content: "供销社是城乡唯一的购物去处：柜台后售货员是体面工作，糖果、雪花膏、的确良是稀罕物。供销社的账本记录着每家每户的供应额度，走后门找关系是常态。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "下乡插队",
      title: "知青岁月",
      key: ["下乡", "知青", "插队", "大队", "生产队"],
      content: "城镇青年下乡插队是时代浪潮：在生产队挣工分，住土坯房，吃大锅饭。知青们一边劳动一边读书，恢复高考的消息传来时，有人激动落泪，有人连夜收拾行李。",
      constant: false,
      selective: false,
      order: 20,
      position: "situation",
      insertionDepth: 60,
      disable: false,
    },
    {
      category: "时代机遇",
      title: "改革开放",
      key: ["高考", "恢复", "包产到户", "个体户", "万元户"],
      content: "时代红利正在释放：1977 年恢复高考，改变一代人命运；农村包产到户，家家有奔头；允许个体经营后，第一批「倒爷」成了万元户。敢想敢干的人，正站在风口上。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "市井生活",
      title: "街坊邻里",
      key: ["邻里", "街坊", "单位", "大院", "筒子楼"],
      content: "街坊邻里抬头不见低头见：谁家添了电视整条街都去围观，婆媳吵架传遍三个胡同。单位分房、评先进、孩子上学，都要靠人情关系。名声坏了，寸步难行。",
      constant: false,
      selective: false,
      order: 30,
      position: "situation",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "家庭成分",
      title: "出身与成分",
      key: ["成分", "出身", "户口", "农民", "工人"],
      content: "出身决定命运：工人家庭吃商品粮，农村户口要挣工分，成分不好的人家处处受排挤。城市户口与农村户口的差距，是那个年代最现实的鸿沟。",
      constant: false,
      selective: false,
      order: 40,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "人间烟火",
      title: "时代细节",
      key: ["缝纫机", "自行车", "收音机", "的确良", "雪花膏"],
      content: "「三转一响」是成家的标配：自行车、缝纫机、手表、收音机。的确良衬衫、雪花膏、蛤蟆镜是时髦的象征。逢年过节才能吃上肉，压岁钱是几毛几分的硬币。",
      constant: false,
      selective: false,
      order: 40,
      position: "situation",
      insertionDepth: 40,
      disable: false,
    },
  ],
};

// 现代都市 - 通用底座（中立舞台，不含任何异能/超自然设定）
const modern: PresetWorldBook = {
  id: "wb-builtin-modern",
  name: "现代都市",
  theme: "现代都市",
  description: "以现实现代城市为蓝本的通用世界：通勤、职场、家庭、社交与城市的日常生活运转。不含异能、修仙、超自然等特殊设定",
  tags: ["现代", "都市", "现实", "通用"],
  violationWords: ["灵气", "异能", "觉醒", "法术", "修仙", "魔法", "御剑", "妖兽", "炼气", "斗气", "魔法阵", "精神力", "灵根", "丹田"],
  entries: [
    {
      category: "世界概要",
      title: "都市日常",
      key: ["现代", "都市", "城市", "生活"],
      content: "这是一个普通的现代城市：写字楼、地铁、商圈、居民区、学校与医院按正常秩序运转。人们上班通勤、吃饭购物、娱乐社交，一切遵循现实世界的社会规则与常识。",
      constant: true,
      selective: false,
      order: 10,
      position: "system",
      insertionDepth: 100,
      disable: false,
    },
    {
      category: "城市地理",
      title: "城市布局",
      key: ["小区", "商圈", "写字楼", "地铁", "街道"],
      content: "城市由多个功能区构成：中央商务区、老城区、住宅区、大学城与近郊。地铁与公交线网覆盖全城，打车与共享单车也是常见出行方式。",
      constant: false,
      selective: false,
      order: 20,
      position: "system",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "社会规则",
      title: "职场规则",
      key: ["公司", "上班", "同事", "领导", "加班", "面试", "裁员"],
      content: "职场遵循现实规则：简历、面试、合同、考勤、项目、KPI。办公室有层级与站队，加班与内卷常见，裁员与跳槽是普通人的现实议题。",
      constant: false,
      selective: false,
      order: 30,
      position: "system",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "社会规则",
      title: "人情世故",
      key: ["相亲", "结婚", "亲戚", "邻居", "同学会", "人情"],
      content: "人际关系遵循现代社会的现实逻辑：家庭有代际摩擦，亲戚有攀比与催婚，邻里保持分寸感，同学会藏着体面与攀比。人情往来有来有往，边界感是成年人的默契。",
      constant: false,
      selective: false,
      order: 40,
      position: "system",
      insertionDepth: 50,
      disable: false,
    },
    {
      category: "经济体系",
      title: "收入与消费",
      key: ["工资", "房租", "房贷", "存款", "物价", "工资卡"],
      content: "经济遵循现实规则：工资月结，房租房贷是主要开支，外卖、网购、会员订阅构成日常消费。普通人面对房价、彩礼、养娃与养老的现实压力。",
      constant: false,
      selective: false,
      order: 50,
      position: "system",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "社会规则",
      title: "法律与秩序",
      key: ["警察", "报警", "合同", "法律", "派出所", "法院"],
      content: "社会运行依靠现实法律与秩序：报警、立案、合同纠纷、劳动仲裁、起诉都是可行的维权路径。警方按流程办案，正义有时迟到但不依靠超自然力量。",
      constant: false,
      selective: false,
      order: 60,
      position: "system",
      insertionDepth: 40,
      disable: false,
    },
    {
      category: "生活方式",
      title: "娱乐社交",
      key: ["聚餐", "KTV", "酒吧", "剧本杀", "演唱会", "追星"],
      content: "休闲娱乐是现实选项：朋友聚餐、KTV、酒吧、剧本杀、密室逃脱、演唱会与追星。社交媒体是日常交流的主阵地，网络舆论能影响现实生活。",
      constant: false,
      selective: false,
      order: 70,
      position: "system",
      insertionDepth: 40,
      disable: false,
    },
  ],
};

export const PRESET_WORLD_BOOKS: PresetWorldBook[] = [
  xianxia,
  fantasy,
  urban,
  modern,
  infinite,
  scifi,
  apocalypse,
  entertainment,
  palace,
  romance,
  folklore,
  rulehorror,
  zhaidou,
  retro,
];
